version: "2.1"

services:
  ProfBeluga-postgres:
    image: postgres:12.4
    container_name: ProfBeluga
    mem_limit: 50m
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "ProfBelugaDB"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - local-bridge

networks:
  local-bridge: # default network
    driver: bridge